### ISSUE TITLE
Remove slf4j-simple dependency

### ISSUE THREAD

**Issue by cimbul** [mwunsch/handlebars.scala#48]
The `handlebars-scala` project depends on both `slf4j-api` and `slf4j-simple`. The latter is an SLF4J binding. This means that any project depending on `handlebars-scala` transitively depends on `slf4j-simple`, which conflicts with any other SLF4J binding they might want to use (e.g., Logback, Log4J).

The [recommended approach for libraries](http://www.slf4j.org/manual.html#libraries) is to depend on `slf4j-api` only. Could you remove the `slf4j-simple` dependency? If you need it for tests, you can always mark it with the `test` scope.

**Comment by timcharper** [comment]
Had to rebase because merge conflict. Merged. Thank you and sorry this was hanging so long!!! Sheesh!
