### ISSUE TITLE
Do you need a new maintainer?

### ISSUE THREAD

**Issue by timcharper** [mwunsch/handlebars.scala#52]
I'm noticing that a lot of the pull-requests and issues are building up. Do you need a new maintainer for this project?

(I mean this in the kindest way possible, having been myself guilty of neglecting pull-requests on my projects at times)

**Comment by chrhicks** [comment]
Tim, I actually think that would be great. I think that's something @mwunsch has to set up though. Hopefully he sees this ping :)

**Comment by mwunsch** [comment]
Hi. Yes probably. @chrhicks what's the state of the [Gilt fork](https://github.com/gilt/handlebars.scala.fork)?

@timcharper happy to add you as a contributor, just want to make sure you start with as clear a picture as possible.

**Comment by chrhicks** [comment]
@mwunsch any changes made to the Gilt fork were bugs related to the 0.0.x (the original) code. Master of handlebars.scala has all of these inherently fixed already. Gilt will also be staying on it's fork for maintenance reasons as it's slowly moving to node / native javascript handlebars.

@timcharper has made most of the contributions lately so I think he'd be great as a contributor.

**Comment by mwunsch** [comment]
Done! Let us know how we can support you @timcharper
